Fix composer cannot install global packages

diff --git a/5.6/Dockerfile b/5.6/Dockerfile
--- a/5.6/Dockerfile
+++ b/5.6/Dockerfile
@@ -1,6 +1,6 @@
 # vim:set ft=dockerfile:
 
-FROM cimg/base:2020.03
+FROM cimg/base:2020.05
 
 LABEL maintainer="Community & Partner Engineering Team <community-partner@circleci.com>"
 
@@ -20,10 +20,19 @@ RUN sudo apt-get update && sudo apt-get install -y \
 	sudo rm -rf /var/lib/apt/lists/*
 
 # Install the PHP package manager Composer
-ENV COMPOSER_VERSION 1.10.1
+ENV COMPOSER_VERSION 1.10.6
 ENV COMPOSER_SHA e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a
 
-RUN sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
-	sudo php -r "if (hash_file('sha384', 'composer-setup.php') === '${COMPOSER_SHA}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
+RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
+	ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
+	if [ "$COMPOSER_SHA" != "$ACTUAL_CHECKSUM" ]; \
+	then \
+		>&2 echo 'ERROR: Invalid installer checksum'; \
+		rm composer-setup.php; \
+		exit 1; \
+	fi && \
 	sudo php composer-setup.php --version=$COMPOSER_VERSION --install-dir=/usr/local/bin --filename=composer && \
-	sudo php -r "unlink('composer-setup.php');"
+	RESULT=$? && \
+	rm composer-setup.php && \
+	sudo chown $(whoami):$(whoami) $HOME/.composer && \
+	exit $RESULT
