Test 7.2.23 respin

diff --git a/7.2/Dockerfile b/7.2/Dockerfile
--- a/7.2/Dockerfile
+++ b/7.2/Dockerfile
@@ -1,10 +1,10 @@
 # vim:set ft=dockerfile:
 
-FROM cimg/base:2020.09
+FROM cimg/base:2021.07
 
 LABEL maintainer="Community & Partner Engineering Team <community-partner@circleci.com>"
 
-ENV PHP_VERSION 7.2.34
+ENV PHP_VERSION 7.2.23
 ENV PHP_MINOR 7.2
 
 RUN sudo add-apt-repository -y ppa:ondrej/php && \
@@ -13,23 +13,27 @@ RUN sudo add-apt-repository -y ppa:ondrej/php && \
 
 # Pre-install a few very popular PHP extensions
 RUN sudo apt-get update && sudo apt-get install -y \
+		php$PHP_MINOR-bcmath \
 		php$PHP_MINOR-curl \
 		php$PHP_MINOR-gd \
-		php$PHP_MINOR-json \
 		php$PHP_MINOR-mbstring \
 		php$PHP_MINOR-mysql \
+		php$PHP_MINOR-pgsql \
+		php$PHP_MINOR-phpdbg \
 		php$PHP_MINOR-xml \
-		php$PHP_MINOR-zip && \
-	sudo rm -rf /var/lib/apt/lists/*
+		php$PHP_MINOR-zip \
+	&& \
+	# Only install the JSON extension in PHP 5 and 7
+	if (( 7 <= 7 )); then \
+		sudo apt-get install -y php$PHP_MINOR-json; \
+	fi && \
+	sudo rm -rf /var/lib/apt/lists/* && \
+	php --version | grep "${PHP_VERSION}" || echo "Error: PHP version installed is not correct." && exit 1
 
 # Install the PHP package manager Composer
-ENV COMPOSER_VERSION 1.10.13
-ENV COMPOSER_SHA 795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc
-
+ENV COMPOSER_VERSION 2.1.7
 RUN sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
-	sudo php -r "if (hash_file('sha384', 'composer-setup.php') === '${COMPOSER_SHA}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
 	sudo php composer-setup.php --version=$COMPOSER_VERSION --install-dir=/usr/local/bin --filename=composer && \
 	sudo php -r "unlink('composer-setup.php');" && \
-	composer --version && \
-	sudo chown -R circleci:circleci ~/.composer
-ENV PATH /home/circleci/.composer/vendor/bin:$PATH
+	composer --version
+ENV PATH /home/circleci/.config/composer/vendor/bin:/home/circleci/.composer/vendor/bin:$PATH
